# Generated by Django 5.0.8 on 2026-04-10 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('game_type', models.CharField(choices=[('memory_match', 'Memory Match'), ('object_discovery', 'Object Discovery'), ('problem_solving', 'Problem Solving'), ('speech_prompt', 'Speech Prompt'), ('matching', 'Matching Game')], max_length=30)),
                ('category', models.CharField(blank=True, default='', help_text='E.g., animal, food, vehicle', max_length=50)),
                ('image', models.ImageField(upload_to='game_images/%Y/%m/')),
                ('emoji', models.CharField(blank=True, default='', help_text='Emoji representation if available', max_length=10)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Searchable tags')),
                ('question', models.TextField(blank=True, default='', help_text='Question for problem solving games')),
                ('correct_answer', models.CharField(blank=True, default='', max_length=200)),
                ('options', models.JSONField(blank=True, default=list, help_text='Multiple choice options')),
                ('hint', models.TextField(blank=True, default='', help_text='Hint for the child')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0, help_text='How many times this image has been used')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['game_type', 'category', 'name'],
                'indexes': [models.Index(fields=['game_type', 'category'], name='therapy_gam_game_ty_a694a5_idx'), models.Index(fields=['game_type', 'difficulty'], name='therapy_gam_game_ty_206e1a_idx'), models.Index(fields=['is_active'], name='therapy_gam_is_acti_98d9d0_idx'), models.Index(fields=['tags'], name='therapy_gam_tags_6e472d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='scenarios/')),
                ('expected_description', models.TextField(help_text='Expected key elements child should describe')),
                ('level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('key_elements', models.JSONField(blank=True, default=list, help_text='List of key things to describe')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['level'], name='therapy_sce_level_6df7e4_idx'), models.Index(fields=['is_active'], name='therapy_sce_is_acti_39f5de_idx')],
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supervision_mode', models.CharField(choices=[('therapist', 'Therapist'), ('caregiver', 'Caregiver'), ('mixed', 'Mixed')], default='therapist', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='therapy_sessions', to='patients.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_therapy_sessions', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='therapy_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionTrial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trial_type', models.CharField(max_length=120)),
                ('prompt', models.TextField(blank=True, default='')),
                ('target_behavior', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='therapy.therapysession')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='therapy.sessiontrial')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='therapy.therapysession')),
            ],
        ),
        migrations.CreateModel(
            name='SceneDescriptionResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('child_response', models.TextField(help_text="Child's description of the scenario")),
                ('llm_feedback', models.TextField(blank=True, default='', help_text='Detailed feedback from LLM')),
                ('llm_score', models.IntegerField(blank=True, help_text='0-100 score from LLM', null=True)),
                ('key_elements_found', models.JSONField(blank=True, default=list, help_text='Which key elements were mentioned')),
                ('clarity_score', models.IntegerField(blank=True, help_text='0-10 clarity/coherence', null=True)),
                ('completeness_score', models.IntegerField(blank=True, help_text='0-10 how complete the description is', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='therapy.scenarioimage')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_responses', to='therapy.sessiontrial')),
            ],
            options={
                'indexes': [models.Index(fields=['trial'], name='therapy_sce_trial_i_7df698_idx'), models.Index(fields=['scenario'], name='therapy_sce_scenari_47bc41_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['child', 'session_date'], name='therapy_the_child_i_68b138_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['therapist', 'session_date'], name='therapy_the_therapi_d5b668_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['status'], name='therapy_the_status_a0aaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['created_at'], name='therapy_the_created_762a56_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontrial',
            index=models.Index(fields=['session', 'created_at'], name='therapy_ses_session_f6c2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontrial',
            index=models.Index(fields=['trial_type'], name='therapy_ses_trial_t_81ec7c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontrial',
            index=models.Index(fields=['status'], name='therapy_ses_status_ea2e00_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['session', 'created_at'], name='therapy_obs_session_feed8e_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['therapist', 'created_at'], name='therapy_obs_therapi_2f5c40_idx'),
        ),
    ]
