# Generated by Django 5.0.8 on 2026-04-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_add_game_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='therapy_gam_child_i_6ed203_idx',
            old_name='therapy_gam_child_i_idx',
        ),
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='therapy_gam_game_id_f72f72_idx',
            old_name='therapy_gam_game_i_idx',
        ),
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='therapy_gam_therapi_18bf5b_idx',
            old_name='therapy_gam_therapi_idx',
        ),
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='therapy_gam_started_219646_idx',
            old_name='therapy_gam_started_idx',
        ),
    ]
