# Generated by Django 5.0.8 on 2026-04-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_rename_therapy_gam_child_i_idx_therapy_gam_child_i_6ed203_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/%Y/%m/'),
        ),
    ]
